# Generated by Django 4.1.5 on 2023-06-04 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150)])),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('worker', 'Worker')], max_length=30)),
            ],
        ),
    ]
