# Generated by Django 4.1.5 on 2023-06-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
