# Generated by Django 4.1.5 on 2023-06-09 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_person_email_alter_person_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('worker', 'Worker')], max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
